apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"