apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: retail
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"   # 👈 apna docker image name check kar lena
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"