apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: retail
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"