apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: retail
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"   # 👈 apna image check kar lena
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"